"""Neural network models for Kirchhoff thin plate PINNs."""

from .multi_subnet_pinn import (
    DEFLECTION_TRANSFORM_CUSTOM,
    DEFLECTION_TRANSFORM_CLAMPED_UNIT_SQUARE,
    DEFLECTION_TRANSFORM_CLAMPED_X_SIMPLE_Y,
    DEFLECTION_TRANSFORM_NAMES,
    DEFLECTION_TRANSFORM_NONE,
    DEFLECTION_TRANSFORM_SIMPLE_X_CLAMPED_Y,
    DEFLECTION_TRANSFORM_UNIT_SQUARE,
    FIELD_NAMES,
    FieldOutputScales,
    GROUPINGS,
    MOMENT_TRANSFORM_NAMES,
    MOMENT_TRANSFORM_NONE,
    MOMENT_TRANSFORM_SIMPLE_ALL_EDGES,
    MOMENT_TRANSFORM_SIMPLE_X_EDGES,
    MOMENT_TRANSFORM_SIMPLE_Y_EDGES,
    MultiSubNetPINN,
    OUTPUT_ACTIVATION_LINEAR,
    OUTPUT_ACTIVATION_NAMES,
    OUTPUT_ACTIVATION_TANH,
)
from .subnet import IndependentSubNet
from .w_pinn import (
    W_PINN_DEFLECTION_TRANSFORM_NAMES,
    WPINN,
)

__all__ = [
    "DEFLECTION_TRANSFORM_CUSTOM",
    "DEFLECTION_TRANSFORM_CLAMPED_X_SIMPLE_Y",
    "DEFLECTION_TRANSFORM_NAMES",
    "DEFLECTION_TRANSFORM_NONE",
    "DEFLECTION_TRANSFORM_SIMPLE_X_CLAMPED_Y",
    "DEFLECTION_TRANSFORM_UNIT_SQUARE",
    "FIELD_NAMES",
    "FieldOutputScales",
    "GROUPINGS",
    "MOMENT_TRANSFORM_NAMES",
    "MOMENT_TRANSFORM_NONE",
    "MOMENT_TRANSFORM_SIMPLE_ALL_EDGES",
    "MOMENT_TRANSFORM_SIMPLE_X_EDGES",
    "MOMENT_TRANSFORM_SIMPLE_Y_EDGES",
    "IndependentSubNet",
    "MultiSubNetPINN",
    "OUTPUT_ACTIVATION_LINEAR",
    "OUTPUT_ACTIVATION_NAMES",
    "OUTPUT_ACTIVATION_TANH",
    "DEFLECTION_TRANSFORM_CLAMPED_UNIT_SQUARE",
    "W_PINN_DEFLECTION_TRANSFORM_NAMES",
    "WPINN",
]
